# Generated by Django 3.1.3 on 2021-01-10 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=50)),
                ('submarks', models.IntegerField(default=0)),
                ('stumarks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='testapp.student')),
            ],
        ),
    ]
