# Generated by Django 3.1.3 on 2021-01-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_submarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empname', models.CharField(max_length=50)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
    ]
