# Generated by Django 3.1.3 on 2021-01-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='Empname',
            new_name='name',
        ),
    ]
