# Generated by Django 3.1.3 on 2021-02-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='randnum',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
