# Generated by Django 3.1.3 on 2021-02-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_company_randnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_ID', models.IntegerField(default=0)),
                ('Staff_ID', models.IntegerField(default=0)),
                ('AMOUNT', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_NAME', models.CharField(max_length=50)),
                ('Staff_AGE', models.IntegerField(default=0)),
                ('STAFF_ADDRESS', models.CharField(max_length=50)),
                ('Monthley_Package', models.IntegerField(default=0)),
            ],
        ),
    ]
