# Generated by Django 3.1.3 on 2021-02-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_payment_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_body', models.CharField(max_length=500)),
                ('stupost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stupost', to='testapp.student')),
            ],
        ),
    ]
