# Generated by Django 3.1.3 on 2021-02-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendname', models.CharField(max_length=50)),
                ('friendid', models.IntegerField(default=0)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='testapp.student')),
            ],
        ),
    ]
